### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by waphle** [sirbrillig/mixed-indent-warning#28] opened 2020-04-30 17:40 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [mixed-indent-warning](https://github.com/sirbrillig/mixed-indent-warning) package 0.3.0

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At C:\Users\jeffz\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11

Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:519246)
    at TextEditor.decorateMarker (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:27540)
    at /packages/mixed-indent-warning/lib/mixed-indent-warning.coffee:51:14
    at Array.forEach (<anonymous>)
    at Object.scanFile (/packages/mixed-indent-warning/lib/mixed-indent-warning.coffee:47:21)
    at /packages/mixed-indent-warning/lib/mixed-indent-warning.coffee:32:14
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1215561)
    at TextBuffer.emitDidStopChangingEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:504974)
    at later (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:104450)
```

### Commands

```
     -5:45.8.0 core:save (input.hidden-input)
     -5:44.7.0 core:backspace (input.hidden-input)
     -5:44.1.0 core:save (input.hidden-input)
 11x -5:24.8.0 core:backspace (input.hidden-input)
     -5:18.2.0 core:save (input.hidden-input)
  5x -0:51.8.0 core:backspace (input.hidden-input)
     -0:45.8.0 core:save (input.hidden-input)
     -0:32 editor:newline (input.hidden-input)
     -0:27.7.0 core:copy (input.hidden-input)
     -0:25.5.0 core:paste (input.hidden-input)
     -0:19.5.0 core:save (input.hidden-input)
     -0:09.5.0 core:move-down (input.hidden-input)
     -0:08.9.0 autocomplete-plus:cancel (input.hidden-input)
     -0:08.6.0 core:move-down (input.hidden-input)
  2x -0:07.8.0 core:backspace (input.hidden-input)
     -0:06.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
autoclose-html 0.23.0 
highlight-selected 0.17.0 
mixed-indent-warning 0.3.0 
open-in-browsers 0.0.30 
platformio-ide-terminal 2.10.0 
pretty-json 2.1.2 
```

**Comment by sirbrillig** [comment] 2020-05-01 15:41
I think this is probably a duplicate of #26, https://github.com/sirbrillig/linter-mixed-indent/issues/19, and https://github.com/sirbrillig/linter-mixed-indent/issues/12 which was fixed in version 1.0. Please upgrade to `linter-mixed-indent`.

**Closed as completed by sirbrillig** 2020-05-01 15:41 UTC
