### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by CohenQU** [sirbrillig/mixed-indent-warning#26] opened 2019-10-13 06:01 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [mixed-indent-warning](https://github.com/sirbrillig/mixed-indent-warning) package 0.3.0

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:519139)
    at TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:27540)
    at /packages/mixed-indent-warning/lib/mixed-indent-warning.coffee:51:14
    at Array.forEach (<anonymous>)
    at Object.scanFile (/packages/mixed-indent-warning/lib/mixed-indent-warning.coffee:47:21)
    at /packages/mixed-indent-warning/lib/mixed-indent-warning.coffee:32:14
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1210649)
    at TextBuffer.emitDidStopChangingEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:504867)
    at later (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:104393)
```

### Commands

```
     -9:20.4.0 snippets:next-tab-stop (input.hidden-input)
     -9:20.4.0 snippets:expand (input.hidden-input)
     -9:20.4.0 editor:indent (input.hidden-input)
     -9:08.4.0 tree-view:remove (span.name.icon.icon-file-directory)
  4x -2:03.3.0 core:copy (input.hidden-input)
     -0:56.6.0 core:paste (input.hidden-input)
     -0:55.1.0 editor:newline (input.hidden-input)
     -0:40.3.0 core:paste (input.hidden-input)
     -0:39 core:backspace (input.hidden-input)
     -0:25 core:paste (input.hidden-input)
     -0:23.1.0 core:backspace (input.hidden-input)
     -0:11.7.0 core:move-right (input.hidden-input)
  4x -0:11.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
linter 2.3.1 
linter-stylelint 4.4.9 
mixed-indent-warning 0.3.0 
open-in-browsers 0.0.30 
platformio-ide-terminal 2.9.4 
pretty-json 2.1.2 
```

**Comment by sirbrillig** [comment] 2019-10-14 15:34
I think this is probably a duplicate of https://github.com/sirbrillig/linter-mixed-indent/issues/19 and https://github.com/sirbrillig/linter-mixed-indent/issues/12 which was fixed in version 1.0.

**Closed as completed by sirbrillig** 2019-10-14 15:34 UTC
