### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by lvcargnini** [sirbrillig/mixed-indent-warning#31] opened 2020-06-04 02:20 UTC
[Enter steps to reproduce:]

1. Just create a clk_wizard don vivado 
2. open the generated SystemVerilog 
3. Copy its content
3. create a systemverilog on Atom
4.Paste in it the content
5. may appear the error or began adjusting it

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 20.04
**Thrown From**: [mixed-indent-warning](https://github.com/sirbrillig/mixed-indent-warning) package 0.3.0

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /usr/share/atom/resources/app/static/<embedded>:11

Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (/usr/share/atom/resources/app/static/<embedded>:11:519494)
    at TextEditor.decorateMarker (/usr/share/atom/resources/app/static/<embedded>:11:27540)
    at /packages/mixed-indent-warning/lib/mixed-indent-warning.coffee:51:14
    at Array.forEach (<anonymous>)
    at Object.scanFile (/packages/mixed-indent-warning/lib/mixed-indent-warning.coffee:47:21)
    at /packages/mixed-indent-warning/lib/mixed-indent-warning.coffee:32:14
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1215907)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1217348)
    at TextBuffer.emitDidStopChangingEvent (/usr/share/atom/resources/app/static/<embedded>:11:505222)
    at later (/usr/share/atom/resources/app/static/<embedded>:14:104450)
```

### Commands

```
  3x -0:44.1.0 core:select-down (input.hidden-input)
     -0:42.9.0 snippets:next-tab-stop (input.hidden-input)
     -0:42.9.0 snippets:expand (input.hidden-input)
     -0:42.9.0 editor:indent (input.hidden-input)
     -0:42.4.0 core:move-right (input.hidden-input)
     -0:41.9.0 core:move-up (input.hidden-input)
     -0:41.6.0 core:move-down (input.hidden-input)
  3x -0:41.4.0 core:move-left (input.hidden-input)
     -0:40.6.0 editor:newline (input.hidden-input)
     -0:39.7.0 snippets:previous-tab-stop (input.hidden-input)
     -0:39.7.0 editor:outdent-selected-rows (input.hidden-input)
  2x -0:27.6.0 intentions:highlight (input.hidden-input)
     -0:24.8.0 core:copy (input.hidden-input)
     -0:24.5.0 find-and-replace:show (input.hidden-input)
     -0:19.3.0 find-and-replace:focus-next (input.hidden-input)
     -0:18.4.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
apio-linter-verilog 0.7.2 
atom-clang-expand 0.1.3 
atom-file-icons 0.7.1 
atom-ide-ui 0.13.0 
atom-pivottable 0.2.0 
atom-visual-studio-code-ui 2.1.0 
autocomplete-python 1.16.0 
build 0.70.0 
build-tclsh 0.6.2 
busy-signal 2.0.1 
clang-format 2.0.8 
clang-tools-extra 0.1.0 
color-indent 1.1.0 
expose 0.15.0 
file-icons 2.1.41 
git-blame 1.8.0 
git-diff-plus 0.4.2 
git-log 0.4.1 
git-plus 8.7.1 
git-plus-toolbar 1.0.1 
git-rebase 0.1.1 
git-split-diff-hyperclick 0.3.12 
git-status 0.3.4 
git-status-utils 0.2.0 
git-time-machine 2.1.0 
hyperclick 0.0.0 
ide-clangd 0.4.0 
ide-python 1.5.0 
ide-vhdl 0.5.0 
indent-guide-ext 0.2.3 
indent-guide-improved 1.4.13 
indentator 1.1.2 
intentions 1.1.5 
language-csv 1.1.2 
language-dashtcl 1.9.1 
language-matlab 0.2.1 
language-matlab-octave 1.0.5 
language-systemverilog 0.12.2 
language-tcl 0.1.2 
language-tcltk 0.1.5 
language-vhdl 0.7.2 
linter 2.3.1 
linter-flake8 2.4.0 
linter-ui-default 1.8.1 
linter-verilator 0.3.0 
linter-vhdl 1.2.0 
mixed-indent-warning 0.3.0 
nyan-indent 0.9.8 
python-indent 1.2.6 
python-tools 0.6.9 
rainbow-csv 1.4.0 
reindent 1.5.0 
split-diff 1.6.1 
structure-view 0.2.1 
systemverilog-browser 1.0.0 
tablr 1.8.3 
tool-bar 1.3.0 
tool-bar-atom 1.7.1 
tree-view-git-status 1.5.3 
verilog-tools 0.1.0 
vhdl-entity-converter 0.9.0 
```

**Comment by sirbrillig** [comment] 2020-06-09 01:21
I think this is probably a duplicate of #26, https://github.com/sirbrillig/linter-mixed-indent/issues/19, and https://github.com/sirbrillig/linter-mixed-indent/issues/12 which was fixed in version 1.0. Please upgrade to `linter-mixed-indent`.

**Closed as completed by sirbrillig** 2020-06-09 01:21 UTC
